name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like AFT to do?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would this help you or other users?
