#!/usr/bin/env bun
/**
 * Capture golden parity fixtures for subc tool translation and formatting.
 *
 * The fixtures are generated by executing the real OpenCode plugin tool
 * handlers with a stub bridge. Translation fixtures record the native command
 * and args sent through callBridge(); format fixtures feed a native response
 * back through the same handlers and record the agent-facing output text.
 *
 * Usage: bun run scripts/capture-subc-parity.ts
 */

import { mkdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BridgePool } from "@cortexkit/aft-bridge";
import type { ToolDefinition } from "@opencode-ai/plugin";
import { createReadTool, hoistedTools } from "../packages/opencode-plugin/src/tools/hoisted.ts";
import { inspectTools } from "../packages/opencode-plugin/src/tools/inspect.ts";
import { readingTools } from "../packages/opencode-plugin/src/tools/reading.ts";
import { searchTools } from "../packages/opencode-plugin/src/tools/search.ts";
import { semanticTools } from "../packages/opencode-plugin/src/tools/semantic.ts";
import type { PluginContext } from "../packages/opencode-plugin/src/types.ts";

const REPO_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const FIXTURES_ROOT = join(REPO_ROOT, "crates/aft/tests/fixtures/subc_parity");
const RAW_PROJECT_ROOT = "/tmp/aft-subc-parity/project";
let PROJECT_ROOT = RAW_PROJECT_ROOT;
const PROJECT_ROOT_TOKEN = "<PROJECT_ROOT>";

type BareToolName = "status" | "read" | "write" | "edit" | "grep" | "search" | "outline" | "inspect";

interface BridgeCall {
  command: string;
  params: Record<string, unknown>;
}

interface TranslateCase {
  name: string;
  tool_name: BareToolName;
  agent_args: Record<string, unknown>;
  diagnostics_on_edit?: boolean;
  expected_error?: string;
}

interface FormatCase {
  name: string;
  tool_name: BareToolName;
  agent_args: Record<string, unknown>;
  native_response_json: Record<string, unknown>;
}

function setupProjectRoot(): void {
  rmSync(RAW_PROJECT_ROOT, { recursive: true, force: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "src"), { recursive: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "docs"), { recursive: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "packages/app"), { recursive: true });
  writeFileSync(join(RAW_PROJECT_ROOT, "README.md"), "# parity\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "src/main.ts"), "const value = 1;\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "docs/guide.md"), "# guide\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "packages/app/index.tsx"), "export const App = () => null;\n", "utf-8");
  PROJECT_ROOT = realpathSync(RAW_PROJECT_ROOT);
}

function sortKeysDeep(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(value as Record<string, unknown>).sort()) {
    sorted[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
  }
  return sorted;
}

function writeJson(path: string, value: unknown, sorted = true): void {
  writeFileSync(path, `${JSON.stringify(sorted ? sortKeysDeep(value) : value, null, 2)}\n`, "utf-8");
}

function replaceProjectRoot(value: unknown): unknown {
  if (typeof value === "string") return value.split(PROJECT_ROOT).join(PROJECT_ROOT_TOKEN);
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(replaceProjectRoot);
  const out: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
    out[key] = replaceProjectRoot(entry);
  }
  return out;
}

function makeRuntime(): Parameters<ToolDefinition["execute"]>[1] {
  return {
    directory: PROJECT_ROOT,
    worktree: PROJECT_ROOT,
    ask: async () => undefined,
  } as Parameters<ToolDefinition["execute"]>[1];
}

function makeCtx(
  calls: BridgeCall[],
  responseForCall: (command: string, params: Record<string, unknown>) => Record<string, unknown>,
  diagnosticsOnEdit = false,
): PluginContext {
  return {
    pool: {
      getBridge: () =>
        ({
          send: async (command: string, params: Record<string, unknown>) => {
            calls.push({ command, params });
            return responseForCall(command, params);
          },
        }) as unknown as ReturnType<BridgePool["getBridge"]>,
    } as unknown as BridgePool,
    client: { lsp: {}, find: {} } as PluginContext["client"],
    config: {
      hoist_builtin_tools: true,
      lsp: { diagnostics_on_edit: diagnosticsOnEdit },
    } as PluginContext["config"],
    storageDir: "/tmp/aft-subc-parity/storage",
  };
}

function tools(ctx: PluginContext): Record<BareToolName, ToolDefinition | undefined> {
  const hoisted = hoistedTools(ctx);
  const grepTools = searchTools(ctx);
  return {
    status: undefined,
    read: createReadTool(ctx),
    write: hoisted.write,
    edit: hoisted.edit,
    grep: grepTools.grep ?? grepTools.aft_grep,
    search: semanticTools(ctx).aft_search,
    outline: readingTools(ctx).aft_outline,
    inspect: inspectTools(ctx).aft_inspect,
  };
}

function successForTranslate(command: string, params: Record<string, unknown>): Record<string, unknown> {
  if (params.preview === true) {
    return { id: "preview", success: true, diff: { before: "", after: "" } };
  }
  if (command === "read") return { id: "translate", success: true, content: "" };
  return { id: "translate", success: true, text: "" };
}

async function captureTranslateCase(caseDef: TranslateCase): Promise<void> {
  const calls: BridgeCall[] = [];
  if (caseDef.expected_error) {
    writeTranslateCase(caseDef, {
      error: { code: "invalid_request", message: caseDef.expected_error },
    });
    return;
  }
  if (caseDef.tool_name === "status") {
    writeTranslateCase(caseDef, { command: "status", args: {} });
    return;
  }

  const ctx = makeCtx(calls, successForTranslate, caseDef.diagnostics_on_edit ?? false);
  const def = tools(ctx)[caseDef.tool_name];
  if (!def) throw new Error(`missing tool ${caseDef.tool_name}`);

  let expected: unknown;
  try {
    await def.execute(caseDef.agent_args, makeRuntime());
    const finalCall = [...calls].reverse().find((call) => call.params.preview !== true) ?? calls.at(-1);
    if (!finalCall) throw new Error(`tool ${caseDef.tool_name} did not call bridge`);
    expected = { command: finalCall.command, args: finalCall.params };
  } catch (error) {
    expected = {
      error: {
        code: "invalid_request",
        message: error instanceof Error ? error.message : String(error),
      },
    };
  }
  writeTranslateCase(caseDef, expected);
}

function writeTranslateCase(caseDef: TranslateCase, expected: unknown): void {
  const dir = join(FIXTURES_ROOT, "translate", caseDef.name);
  mkdirSync(dir, { recursive: true });
  writeJson(join(dir, "input.json"), {
    tool_name: caseDef.tool_name,
    agent_args: caseDef.agent_args,
    project_root: PROJECT_ROOT_TOKEN,
    ...(caseDef.diagnostics_on_edit === undefined
      ? {}
      : { diagnostics_on_edit: caseDef.diagnostics_on_edit }),
  });
  writeJson(join(dir, "expected.json"), replaceProjectRoot(expected));
}

async function captureFormatCase(caseDef: FormatCase): Promise<void> {
  let expected: string;
  if (caseDef.tool_name === "status") {
    expected = formatStatus(caseDef.native_response_json);
  } else {
    const calls: BridgeCall[] = [];
    const ctx = makeCtx(calls, (_command, params) => {
      if (params.preview === true) {
        return { id: "preview", success: true, diff: { before: "old\n", after: "new\n" } };
      }
      return caseDef.native_response_json;
    });
    const def = tools(ctx)[caseDef.tool_name];
    if (!def) throw new Error(`missing tool ${caseDef.tool_name}`);
    try {
      const result = await def.execute(caseDef.agent_args, makeRuntime());
      expected = typeof result === "string" ? result : String((result as { output?: unknown }).output ?? "");
    } catch (error) {
      expected = error instanceof Error ? error.message : String(error);
    }
  }
  const dir = join(FIXTURES_ROOT, "format", caseDef.name);
  mkdirSync(dir, { recursive: true });
  writeJson(
    join(dir, "input.json"),
    {
      tool_name: caseDef.tool_name,
      native_response_json: caseDef.native_response_json,
      ctx: {
        agent_args: caseDef.agent_args,
        project_root: PROJECT_ROOT_TOKEN,
      },
    },
    false,
  );
  writeFileSync(join(dir, "expected.txt"), expected.split(PROJECT_ROOT).join(PROJECT_ROOT_TOKEN), "utf-8");
}

function formatStatus(response: Record<string, unknown>): string {
  const text = response.text;
  if (typeof text === "string" && text.length > 0) return text;
  const { id: _id, success: _success, ...data } = response;
  return JSON.stringify(data, null, 2);
}

const TRANSLATE_CASES: TranslateCase[] = [
  { name: "status_empty", tool_name: "status", agent_args: {} },
  { name: "read_offset_limit", tool_name: "read", agent_args: { filePath: "src/../README.md", offset: 2, limit: 3 } },
  { name: "write_default_diagnostics", tool_name: "write", agent_args: { filePath: "src/new.ts", content: "export {};\n" } },
  { name: "write_diagnostics_true", tool_name: "write", diagnostics_on_edit: true, agent_args: { filePath: "src/new.ts", content: "export {};\n" } },
  { name: "edit_append", tool_name: "edit", diagnostics_on_edit: true, agent_args: { filePath: "src/main.ts", appendContent: "\nexport {};\n" } },
  { name: "edit_batch", tool_name: "edit", agent_args: { filePath: "src/main.ts", edits: [{ oldString: "value", newString: "answer", startLine: 1, endLine: 1 }] } },
  { name: "edit_symbol", tool_name: "edit", agent_args: { filePath: "src/main.ts", symbol: "value", content: "const value = 2;" } },
  { name: "edit_replace_occurrence_zero", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "value", newString: "answer", occurrence: 0 } },
  { name: "grep_include_braces", tool_name: "grep", agent_args: { pattern: "value", include: "*.ts,**/*.{vue,tsx}" } },
  { name: "grep_multi_path_existing_and_missing", tool_name: "grep", agent_args: { pattern: "value", path: "src docs missing-dir" } },
  { name: "search_default", tool_name: "search", agent_args: { query: "value" } },
  { name: "search_include_tests", tool_name: "search", agent_args: { query: "fixtures", topK: 7, includeTests: true } },
  { name: "search_whitespace_error", tool_name: "search", agent_args: { query: "   " } },
  { name: "search_invalid_topk", tool_name: "search", expected_error: "topK must be between 1 and 100", agent_args: { query: "value", topK: -1 } },
  { name: "inspect_scope_topk", tool_name: "inspect", agent_args: { sections: ["diagnostics"], scope: ["src", "docs"], topK: 5 } },
  { name: "inspect_invalid_topk", tool_name: "inspect", expected_error: "topK must be an integer between 1 and 100", agent_args: { topK: 1.5 } },
  { name: "outline_url", tool_name: "outline", agent_args: { target: "https://example.com/doc" } },
  { name: "outline_url_files_mode", tool_name: "outline", agent_args: { target: "https://example.com/doc", files: true } },
  { name: "outline_array_files", tool_name: "outline", agent_args: { target: ["src", "docs"], files: true } },
  { name: "outline_directory_json_mode", tool_name: "outline", agent_args: { target: "src" } },
];

const FORMAT_CASES: FormatCase[] = [
  { name: "status_text", tool_name: "status", agent_args: {}, native_response_json: { id: "1", success: true, text: "indexes ready" } },
  { name: "read_truncated_footer", tool_name: "read", agent_args: { filePath: "README.md" }, native_response_json: { id: "1", success: true, content: "1: hello\n", truncated: true, start_line: 1, end_line: 100, total_lines: 250 } },
  { name: "read_range_no_footer", tool_name: "read", agent_args: { filePath: "README.md", startLine: 1 }, native_response_json: { id: "1", success: true, content: "1: hello\n", truncated: true, start_line: 1, end_line: 100, total_lines: 250 } },
  { name: "read_image_attachment", tool_name: "read", agent_args: { filePath: "image.png" }, native_response_json: { id: "1", success: true, attachments: [{ kind: "image", mime: "image/png", data: "iVBORw0KGgo=", bytes: 245760, base64_bytes: 12, width: 1024, height: 768, resized: true, animation: "none", orientation_applied: false }] } },
  { name: "write_created", tool_name: "write", agent_args: { filePath: "src/new.ts", content: "export {};\n" }, native_response_json: { id: "1", success: true, created: true, diff: { additions: 1, deletions: 0 } } },
  { name: "write_no_op_lsp", tool_name: "write", agent_args: { filePath: "src/main.ts", content: "const value = 1;\n" }, native_response_json: { id: "1", success: true, created: false, formatted: true, no_op: true, lsp_diagnostics: [{ severity: "error", line: 3, message: "Type mismatch" }], lsp_pending_servers: ["typescript"], lsp_exited_servers: ["eslint"] } },
  { name: "write_rolled_back", tool_name: "write", agent_args: { filePath: "src/main.ts", content: "{" }, native_response_json: { id: "1", success: true, rolled_back: true } },
  { name: "edit_no_op_lsp", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "value", newString: "value" }, native_response_json: { id: "1", success: true, replacements: 1, no_op: true, diff: { additions: 0, deletions: 0 }, format_skip_reasons: ["unsupported_language", "timeout", "error", "timeout"], lsp_diagnostics: [{ severity: "warning", line: 1, message: "warn" }, { severity: "error", line: 2, message: "bad" }], lsp_pending_servers: ["typescript"] } },
  { name: "edit_glob_summary", tool_name: "edit", agent_args: { filePath: "src/**/*.ts", oldString: "value", newString: "answer", replaceAll: true }, native_response_json: { id: "1", success: true, total_files: 2, total_replacements: 3 } },
  { name: "grep_text", tool_name: "grep", agent_args: { pattern: "value" }, native_response_json: { id: "1", success: true, text: "src/main.ts:1: const value = 1;" } },
  { name: "grep_matches_fallback", tool_name: "grep", agent_args: { pattern: "value" }, native_response_json: { id: "1", success: true, matches: [{ file: "src/main.ts", line: 1, line_text: "const value = 1;" }], total_matches: 1, files_with_matches: 1 } },
  { name: "grep_empty_fallback", tool_name: "grep", agent_args: { pattern: "missing" }, native_response_json: { id: "1", success: true, matches: [], total_matches: 0, files_with_matches: 0 } },
  { name: "search_text_honesty", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: true, text: "1. src/main.ts", more_available: true, fully_degraded: true, complete: false } },
  { name: "search_no_text_honesty", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: true, more_available: true, engine_capped: true, fully_degraded: true, complete: false } },
  { name: "search_error", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: false, code: "semantic_unavailable", message: "semantic index unavailable" } },
  { name: "outline_text_skipped", tool_name: "outline", agent_args: { target: "src/main.ts" }, native_response_json: { id: "1", success: true, text: "main.ts\n  fn main", skipped_files: [{ file: "bad.ts", reason: "parse error" }] } },
  { name: "outline_files_partial", tool_name: "outline", agent_args: { target: "src", files: true }, native_response_json: { id: "1", success: true, text: "src/main.ts", complete: false, unchecked_files: ["src/big.ts"] } },
  { name: "outline_directory_json", tool_name: "outline", agent_args: { target: "src" }, native_response_json: { id: "1", success: true, complete: true, text: "directory outline" } },
  { name: "inspect_text_diagnostics", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, text: "todos: 2", summary: { diagnostics: { errors: 1, warnings: 2, info: 0, hints: 0 } }, details: { diagnostics: [{ file: "src/main.ts", line: 1, column: 2, severity: "error", message: "boom", source: "tsserver" }] } } },
  { name: "inspect_no_text_fallback", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, summary: { diagnostics: { errors: 0, warnings: 1, info: 0, hints: 0 } } } },
  { name: "inspect_duplicate_guard", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, text: "summary\nDiagnostics: already rendered", summary: { diagnostics: { errors: 1, warnings: 0, info: 0, hints: 0 } } } },
  { name: "edit_error_message_only", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "x", newString: "y" }, native_response_json: { id: "1", success: false, code: "invalid_request", message: "edit failed clearly" } },
];

setupProjectRoot();
rmSync(FIXTURES_ROOT, { recursive: true, force: true });
mkdirSync(FIXTURES_ROOT, { recursive: true });

for (const caseDef of TRANSLATE_CASES) {
  await captureTranslateCase(caseDef);
}
for (const caseDef of FORMAT_CASES) {
  await captureFormatCase(caseDef);
}

console.log(
  `Wrote ${TRANSLATE_CASES.length} translate cases and ${FORMAT_CASES.length} format cases under ${FIXTURES_ROOT}`,
);
