#!/usr/bin/env bun
/**
 * Capture golden parity fixtures for subc tool translation and formatting.
 *
 * The fixtures are generated by executing the real OpenCode plugin tool
 * handlers with a stub bridge. Translation fixtures record the native command
 * and args sent through callBridge(); format fixtures feed a native response
 * back through the same handlers and record the agent-facing output text.
 *
 * Usage: bun run scripts/capture-subc-parity.ts [--only fixture-name-substring]
 */

import { mkdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BridgePool } from "@cortexkit/aft-bridge";
import type { ToolDefinition } from "@opencode-ai/plugin";
import { createReadTool, hoistedTools } from "../packages/opencode-plugin/src/tools/hoisted.ts";
import { inspectTools } from "../packages/opencode-plugin/src/tools/inspect.ts";
import { navigationTools } from "../packages/opencode-plugin/src/tools/navigation.ts";
import { readingTools } from "../packages/opencode-plugin/src/tools/reading.ts";
import { searchTools } from "../packages/opencode-plugin/src/tools/search.ts";
import { semanticTools } from "../packages/opencode-plugin/src/tools/semantic.ts";
import type { PluginContext } from "../packages/opencode-plugin/src/types.ts";

const REPO_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const FIXTURES_ROOT = join(REPO_ROOT, "crates/aft/tests/fixtures/subc_parity");
const RAW_PROJECT_ROOT = "/tmp/aft-subc-parity/project";
let PROJECT_ROOT = RAW_PROJECT_ROOT;
const PROJECT_ROOT_TOKEN = "<PROJECT_ROOT>";
const HOME_ROOT = homedir();
const HOME_ROOT_TOKEN = "<HOME>";

type BareToolName = "status" | "read" | "write" | "edit" | "grep" | "search" | "outline" | "zoom" | "inspect" | "callgraph";

interface BridgeCall {
  command: string;
  params: Record<string, unknown>;
}

interface TranslateCase {
  name: string;
  tool_name: BareToolName;
  agent_args: Record<string, unknown>;
  diagnostics_on_edit?: boolean;
  expected_error?: string;
}

interface FormatCase {
  name: string;
  tool_name: BareToolName;
  agent_args: Record<string, unknown>;
  native_response_json: Record<string, unknown>;
}

function setupProjectRoot(): void {
  rmSync(RAW_PROJECT_ROOT, { recursive: true, force: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "src"), { recursive: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "docs"), { recursive: true });
  mkdirSync(join(RAW_PROJECT_ROOT, "packages/app"), { recursive: true });
  writeFileSync(join(RAW_PROJECT_ROOT, "README.md"), "# parity\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "src/main.ts"), "const value = 1;\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "docs/guide.md"), "# guide\n", "utf-8");
  writeFileSync(join(RAW_PROJECT_ROOT, "packages/app/index.tsx"), "export const App = () => null;\n", "utf-8");
  PROJECT_ROOT = realpathSync(RAW_PROJECT_ROOT);
}

function sortKeysDeep(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(value as Record<string, unknown>).sort()) {
    sorted[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
  }
  return sorted;
}

function writeJson(path: string, value: unknown, sorted = true): void {
  writeFileSync(path, `${JSON.stringify(sorted ? sortKeysDeep(value) : value, null, 2)}\n`, "utf-8");
}

function replaceStablePaths(value: unknown): unknown {
  if (typeof value === "string") {
    return value
      .split(PROJECT_ROOT)
      .join(PROJECT_ROOT_TOKEN)
      .split(RAW_PROJECT_ROOT)
      .join(PROJECT_ROOT_TOKEN)
      .split(HOME_ROOT)
      .join(HOME_ROOT_TOKEN);
  }
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(replaceStablePaths);
  const out: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
    out[key] = replaceStablePaths(entry);
  }
  return out;
}

function makeRuntime(): Parameters<ToolDefinition["execute"]>[1] {
  const runtime = {
    directory: PROJECT_ROOT,
    worktree: PROJECT_ROOT,
    ask: async () => undefined,
  };
  return runtime as unknown as Parameters<ToolDefinition["execute"]>[1];
}

function makeCtx(
  calls: BridgeCall[],
  responseForCall: (command: string, params: Record<string, unknown>) => Record<string, unknown>,
  diagnosticsOnEdit = false,
): PluginContext {
  return {
    pool: {
      getBridge: () =>
        ({
          send: async (command: string, params: Record<string, unknown>) => {
            calls.push({ command, params });
            return responseForCall(command, params);
          },
        }) as unknown as ReturnType<BridgePool["getBridge"]>,
    } as unknown as BridgePool,
    client: { lsp: {}, find: {} } as PluginContext["client"],
    config: {
      hoist_builtin_tools: true,
      lsp: { diagnostics_on_edit: diagnosticsOnEdit },
    } as PluginContext["config"],
    storageDir: "/tmp/aft-subc-parity/storage",
  };
}

function tools(ctx: PluginContext): Record<BareToolName, ToolDefinition | undefined> {
  const hoisted = hoistedTools(ctx);
  const grepTools = searchTools(ctx);
  return {
    status: undefined,
    read: createReadTool(ctx),
    write: hoisted.write,
    edit: hoisted.edit,
    grep: grepTools.grep ?? grepTools.aft_grep,
    search: semanticTools(ctx).aft_search,
    outline: readingTools(ctx).aft_outline,
    zoom: readingTools(ctx).aft_zoom,
    inspect: inspectTools(ctx).aft_inspect,
    callgraph: navigationTools(ctx).aft_callgraph,
  };
}

function successForTranslate(command: string, params: Record<string, unknown>): Record<string, unknown> {
  if (params.preview === true) {
    return { id: "preview", success: true, diff: { before: "", after: "" } };
  }
  if (command === "read") return { id: "translate", success: true, content: "" };
  return { id: "translate", success: true, text: "" };
}

function zoomTargetEntries(agentArgs: Record<string, unknown>): Array<{ filePath: string; symbol: string }> | undefined {
  const rawTargets = agentArgs.targets;
  const targets = Array.isArray(rawTargets) ? rawTargets : rawTargets ? [rawTargets] : undefined;
  if (!targets) return undefined;
  return targets.map((entry) => {
    const obj = entry as { filePath?: unknown; symbol?: unknown };
    return { filePath: String(obj.filePath ?? ""), symbol: String(obj.symbol ?? "") };
  });
}

function expectedZoomMultiTargetTranslate(
  caseDef: TranslateCase,
  calls: BridgeCall[],
): Record<string, unknown> | undefined {
  if (caseDef.tool_name !== "zoom") return undefined;
  const targets = zoomTargetEntries(caseDef.agent_args);
  if (!targets || targets.length === 0) return undefined;

  const zoomCalls = calls.filter((call) => call.command === "zoom" && call.params.preview !== true);
  if (zoomCalls.length !== targets.length) {
    throw new Error(
      `zoom multi-target case ${caseDef.name} expected ${targets.length} zoom calls, got ${zoomCalls.length}`,
    );
  }

  const args: Record<string, unknown> = {
    targets: targets.map((target, index) => ({
      file: zoomCalls[index]?.params.file,
      symbol: zoomCalls[index]?.params.symbol,
      target_label: target.filePath,
    })),
  };
  const firstParams = zoomCalls[0]?.params ?? {};
  if (firstParams.context_lines !== undefined) args.context_lines = firstParams.context_lines;
  if (firstParams.callgraph === true) args.callgraph = true;
  return { command: "zoom", args };
}

function zoomMultiTargetResponses(
  response: Record<string, unknown>,
): Array<Record<string, unknown>> | undefined {
  const targets = response.targets;
  if (!Array.isArray(targets)) return undefined;
  return targets.map((entry) => {
    const response = (entry as { response?: unknown }).response;
    return response && typeof response === "object" && !Array.isArray(response)
      ? (response as Record<string, unknown>)
      : { success: false, message: "missing zoom response" };
  });
}

async function captureTranslateCase(caseDef: TranslateCase): Promise<void> {
  const calls: BridgeCall[] = [];
  if (caseDef.expected_error) {
    writeTranslateCase(caseDef, {
      error: { code: "invalid_request", message: caseDef.expected_error },
    });
    return;
  }
  if (caseDef.tool_name === "status") {
    writeTranslateCase(caseDef, { command: "status", args: {} });
    return;
  }

  const ctx = makeCtx(calls, successForTranslate, caseDef.diagnostics_on_edit ?? false);
  const def = tools(ctx)[caseDef.tool_name];
  if (!def) throw new Error(`missing tool ${caseDef.tool_name}`);

  let expected: unknown;
  try {
    await def.execute(caseDef.agent_args, makeRuntime());
    expected = expectedZoomMultiTargetTranslate(caseDef, calls);
    if (!expected) {
      const finalCall = [...calls].reverse().find((call) => call.params.preview !== true) ?? calls.at(-1);
      if (!finalCall) throw new Error(`tool ${caseDef.tool_name} did not call bridge`);
      expected = { command: finalCall.command, args: finalCall.params };
    }
  } catch (error) {
    expected = {
      error: {
        code: "invalid_request",
        message: error instanceof Error ? error.message : String(error),
      },
    };
  }
  writeTranslateCase(caseDef, expected);
}

function writeTranslateCase(caseDef: TranslateCase, expected: unknown): void {
  const dir = join(FIXTURES_ROOT, "translate", caseDef.name);
  mkdirSync(dir, { recursive: true });
  writeJson(join(dir, "input.json"), {
    tool_name: caseDef.tool_name,
    agent_args: caseDef.agent_args,
    project_root: PROJECT_ROOT_TOKEN,
    ...(caseDef.diagnostics_on_edit === undefined
      ? {}
      : { diagnostics_on_edit: caseDef.diagnostics_on_edit }),
  });
  writeJson(join(dir, "expected.json"), replaceStablePaths(expected));
}

async function captureFormatCase(caseDef: FormatCase): Promise<void> {
  let expected: string;
  if (caseDef.tool_name === "status") {
    expected = formatStatus(caseDef.native_response_json);
  } else {
    const calls: BridgeCall[] = [];
    const multiTargetResponses = zoomMultiTargetResponses(caseDef.native_response_json);
    let multiTargetIndex = 0;
    const ctx = makeCtx(calls, (command, params) => {
      if (params.preview === true) {
        return { id: "preview", success: true, diff: { before: "old\n", after: "new\n" } };
      }
      if (caseDef.tool_name === "zoom" && command === "zoom" && multiTargetResponses) {
        return multiTargetResponses[multiTargetIndex++] ?? { success: false, message: "missing zoom response" };
      }
      return caseDef.native_response_json;
    });
    const def = tools(ctx)[caseDef.tool_name];
    if (!def) throw new Error(`missing tool ${caseDef.tool_name}`);
    try {
      const result = await def.execute(caseDef.agent_args, makeRuntime());
      expected = typeof result === "string" ? result : String((result as { output?: unknown }).output ?? "");
    } catch (error) {
      expected = error instanceof Error ? error.message : String(error);
    }
  }
  const dir = join(FIXTURES_ROOT, "format", caseDef.name);
  mkdirSync(dir, { recursive: true });
  writeJson(
    join(dir, "input.json"),
    {
      tool_name: caseDef.tool_name,
      native_response_json: replaceStablePaths(caseDef.native_response_json),
      ctx: {
        agent_args: replaceStablePaths(caseDef.agent_args),
        project_root: PROJECT_ROOT_TOKEN,
      },
    },
    false,
  );
  writeFileSync(join(dir, "expected.txt"), replaceStablePaths(expected) as string, "utf-8");
}

function formatStatus(response: Record<string, unknown>): string {
  const text = response.text;
  if (typeof text === "string" && text.length > 0) return text;
  const { id: _id, success: _success, ...data } = response;
  return JSON.stringify(data, null, 2);
}

const TRANSLATE_CASES: TranslateCase[] = [
  { name: "status_empty", tool_name: "status", agent_args: {} },
  { name: "read_offset_limit", tool_name: "read", agent_args: { filePath: "src/../README.md", offset: 2, limit: 3 } },
  { name: "write_default_diagnostics", tool_name: "write", agent_args: { filePath: "src/new.ts", content: "export {};\n" } },
  { name: "write_diagnostics_true", tool_name: "write", diagnostics_on_edit: true, agent_args: { filePath: "src/new.ts", content: "export {};\n" } },
  { name: "edit_append", tool_name: "edit", diagnostics_on_edit: true, agent_args: { filePath: "src/main.ts", appendContent: "\nexport {};\n" } },
  { name: "edit_batch", tool_name: "edit", agent_args: { filePath: "src/main.ts", edits: [{ oldString: "value", newString: "answer", startLine: 1, endLine: 1 }] } },
  { name: "edit_symbol", tool_name: "edit", agent_args: { filePath: "src/main.ts", symbol: "value", content: "const value = 2;" } },
  { name: "edit_replace_occurrence_zero", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "value", newString: "answer", occurrence: 0 } },
  { name: "grep_include_braces", tool_name: "grep", agent_args: { pattern: "value", include: "*.ts,**/*.{vue,tsx}" } },
  { name: "grep_multi_path_existing_and_missing", tool_name: "grep", agent_args: { pattern: "value", path: "src docs missing-dir" } },
  { name: "search_default", tool_name: "search", agent_args: { query: "value" } },
  { name: "search_include_tests", tool_name: "search", agent_args: { query: "fixtures", topK: 7, includeTests: true } },
  { name: "search_whitespace_error", tool_name: "search", agent_args: { query: "   " } },
  { name: "search_invalid_topk", tool_name: "search", expected_error: "topK must be between 1 and 100", agent_args: { query: "value", topK: -1 } },
  { name: "inspect_scope_topk", tool_name: "inspect", agent_args: { sections: ["diagnostics"], scope: ["src", "docs"], topK: 5 } },
  { name: "inspect_invalid_topk", tool_name: "inspect", expected_error: "topK must be an integer between 1 and 100", agent_args: { topK: 1.5 } },
  { name: "outline_url", tool_name: "outline", agent_args: { target: "https://example.com/doc" } },
  { name: "outline_url_files_mode", tool_name: "outline", agent_args: { target: "https://example.com/doc", files: true } },
  { name: "outline_array_files", tool_name: "outline", agent_args: { target: ["src", "docs"], files: true } },
  { name: "outline_directory_json_mode", tool_name: "outline", agent_args: { target: "src" } },
  { name: "outline_directory_include_tests", tool_name: "outline", agent_args: { target: "src", includeTests: true } },
  { name: "zoom_url_translate", tool_name: "zoom", agent_args: { url: "https://example.com/doc", symbols: "Features", contextLines: 2 } },
  { name: "zoom_single_symbol_translate", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "run", contextLines: 2, callgraph: true } },
  { name: "zoom_multi_symbol_batch_translate", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: ["run", "missing"] } },
  { name: "zoom_multitarget_all_success_translate", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "docs/guide.md", symbol: "Guide" }], contextLines: 2, callgraph: true } },
  { name: "zoom_multitarget_partial_translate", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "docs/guide.md", symbol: "missing" }] } },
  { name: "zoom_multitarget_file_error_translate", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "missing.ts", symbol: "run" }] } },
  { name: "callgraph_callers_translate", tool_name: "callgraph", agent_args: { op: "callers", filePath: "src/main.ts", symbol: "run", depth: 2, includeTests: true } },
  { name: "callgraph_call_tree_translate", tool_name: "callgraph", agent_args: { op: "call_tree", filePath: "src/main.ts", symbol: "run", depth: 3 } },
  { name: "callgraph_trace_to_translate", tool_name: "callgraph", agent_args: { op: "trace_to", filePath: "src/main.ts", symbol: "handler", depth: 4, includeTests: false } },
  { name: "callgraph_trace_to_symbol_translate", tool_name: "callgraph", agent_args: { op: "trace_to_symbol", filePath: "src/main.ts", symbol: "handler", toSymbol: "leaf", toFile: "src/main.ts", depth: 6 } },
  { name: "callgraph_impact_translate", tool_name: "callgraph", agent_args: { op: "impact", filePath: "src/main.ts", symbol: "run", depth: 5 } },
  { name: "callgraph_trace_data_translate", tool_name: "callgraph", agent_args: { op: "trace_data", filePath: "src/main.ts", symbol: "run", expression: "value", depth: 2 } },
];

const FORMAT_CASES: FormatCase[] = [
  { name: "status_text", tool_name: "status", agent_args: {}, native_response_json: { id: "1", success: true, text: "indexes ready" } },
  { name: "read_truncated_footer", tool_name: "read", agent_args: { filePath: "README.md" }, native_response_json: { id: "1", success: true, content: "1: hello\n", truncated: true, start_line: 1, end_line: 100, total_lines: 250 } },
  { name: "read_range_no_footer", tool_name: "read", agent_args: { filePath: "README.md", startLine: 1 }, native_response_json: { id: "1", success: true, content: "1: hello\n", truncated: true, start_line: 1, end_line: 100, total_lines: 250 } },
  { name: "read_image_attachment", tool_name: "read", agent_args: { filePath: "image.png" }, native_response_json: { id: "1", success: true, attachments: [{ kind: "image", mime: "image/png", data: "iVBORw0KGgo=", bytes: 245760, base64_bytes: 12, width: 1024, height: 768, resized: true, animation: "none", orientation_applied: false }] } },
  { name: "write_created", tool_name: "write", agent_args: { filePath: "src/new.ts", content: "export {};\n" }, native_response_json: { id: "1", success: true, created: true, diff: { additions: 1, deletions: 0 } } },
  { name: "write_no_op_lsp", tool_name: "write", agent_args: { filePath: "src/main.ts", content: "const value = 1;\n" }, native_response_json: { id: "1", success: true, created: false, formatted: true, no_op: true, lsp_diagnostics: [{ severity: "error", line: 3, message: "Type mismatch" }], lsp_pending_servers: ["typescript"], lsp_exited_servers: ["eslint"] } },
  { name: "write_rolled_back", tool_name: "write", agent_args: { filePath: "src/main.ts", content: "{" }, native_response_json: { id: "1", success: true, rolled_back: true } },
  { name: "edit_no_op_lsp", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "value", newString: "value" }, native_response_json: { id: "1", success: true, replacements: 1, no_op: true, diff: { additions: 0, deletions: 0 }, format_skip_reasons: ["unsupported_language", "timeout", "error", "timeout"], lsp_diagnostics: [{ severity: "warning", line: 1, message: "warn" }, { severity: "error", line: 2, message: "bad" }], lsp_pending_servers: ["typescript"] } },
  { name: "edit_glob_summary", tool_name: "edit", agent_args: { filePath: "src/**/*.ts", oldString: "value", newString: "answer", replaceAll: true }, native_response_json: { id: "1", success: true, total_files: 2, total_replacements: 3 } },
  { name: "grep_text", tool_name: "grep", agent_args: { pattern: "value" }, native_response_json: { id: "1", success: true, text: "src/main.ts:1: const value = 1;" } },
  { name: "grep_matches_fallback", tool_name: "grep", agent_args: { pattern: "value" }, native_response_json: { id: "1", success: true, matches: [{ file: "src/main.ts", line: 1, line_text: "const value = 1;" }], total_matches: 1, files_with_matches: 1 } },
  { name: "grep_empty_fallback", tool_name: "grep", agent_args: { pattern: "missing" }, native_response_json: { id: "1", success: true, matches: [], total_matches: 0, files_with_matches: 0 } },
  { name: "search_text_honesty", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: true, text: "1. src/main.ts", more_available: true, fully_degraded: true, complete: false } },
  { name: "search_no_text_honesty", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: true, more_available: true, engine_capped: true, fully_degraded: true, complete: false } },
  { name: "search_error", tool_name: "search", agent_args: { query: "value" }, native_response_json: { id: "1", success: false, code: "semantic_unavailable", message: "semantic index unavailable" } },
  { name: "outline_text_skipped", tool_name: "outline", agent_args: { target: "src/main.ts" }, native_response_json: { id: "1", success: true, text: "main.ts\n  fn main", skipped_files: [{ file: "bad.ts", reason: "parse error" }] } },
  { name: "outline_files_partial", tool_name: "outline", agent_args: { target: "src", files: true }, native_response_json: { id: "1", success: true, text: "src/main.ts", complete: false, unchecked_files: ["src/big.ts"] } },
  { name: "outline_directory_json", tool_name: "outline", agent_args: { target: "src" }, native_response_json: { id: "1", success: true, complete: true, text: "directory outline" } },
  { name: "inspect_text_diagnostics", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, text: "todos: 2", summary: { diagnostics: { errors: 1, warnings: 2, info: 0, hints: 0 } }, details: { diagnostics: [{ file: "src/main.ts", line: 1, column: 2, severity: "error", message: "boom", source: "tsserver" }] } } },
  { name: "inspect_no_text_fallback", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, summary: { diagnostics: { errors: 0, warnings: 1, info: 0, hints: 0 } } } },
  { name: "inspect_duplicate_guard", tool_name: "inspect", agent_args: {}, native_response_json: { id: "1", success: true, text: "summary\nDiagnostics: already rendered", summary: { diagnostics: { errors: 1, warnings: 0, info: 0, hints: 0 } } } },
  { name: "edit_error_message_only", tool_name: "edit", agent_args: { filePath: "src/main.ts", oldString: "x", newString: "y" }, native_response_json: { id: "1", success: false, code: "invalid_request", message: "edit failed clearly" } },
  { name: "zoom_url_format", tool_name: "zoom", agent_args: { url: "https://example.com/doc", symbols: "Features" }, native_response_json: { id: "1", success: true, name: "Features", kind: "heading", range: { start_line: 5, end_line: 7 }, content: "## Features\n\nFeature details live here.", context_before: ["Intro paragraph for the document.", ""], context_after: ["### Fast Path"], annotations: { calls_out: [], called_by: [] } } },
  { name: "zoom_single_symbol_callgraph_format", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "run", callgraph: true }, native_response_json: { id: "1", success: true, name: "run", kind: "function", range: { start_line: 10, end_line: 12 }, content: "function run() {\n  helper();\n}", context_before: ["const value = 1;"], context_after: ["run();"], annotations: { calls_out: [{ name: "helper", line: 11, extra_count: 2 }], called_by: [{ name: "main", line: 20 }] } } },
  { name: "zoom_multi_symbol_batch_format", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "run missing" }, native_response_json: { id: "1", success: true, complete: false, symbols: [{ name: "run", response: { id: "run", success: true, name: "run", kind: "function", range: { start_line: 1, end_line: 3 }, content: "function run() {\n  return 1;\n}", context_before: [], context_after: [], annotations: { calls_out: [], called_by: [] } } }, { name: "missing", response: { id: "missing", success: false, code: "symbol_not_found", message: "symbol 'missing' not found" } }] } },
  { name: "zoom_multitarget_all_success_format", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "docs/guide.md", symbol: "Guide" }], callgraph: true }, native_response_json: { id: "1", success: true, targets: [{ targetLabel: "src/main.ts", name: "run", response: { id: "run", success: true, name: "run", kind: "function", range: { start_line: 1, end_line: 3 }, content: "function run() {\n  helper();\n}", context_before: [], context_after: [], annotations: { calls_out: [{ name: "helper", line: 2 }], called_by: [] } } }, { targetLabel: "docs/guide.md", name: "Guide", response: { id: "guide", success: true, name: "Guide", kind: "heading", range: { start_line: 5, end_line: 6 }, content: "## Guide\nDetails.", context_before: ["# parity"], context_after: [], annotations: { calls_out: [], called_by: [] } } }] } },
  { name: "zoom_multitarget_partial_format", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "docs/guide.md", symbol: "missing" }] }, native_response_json: { id: "1", success: true, targets: [{ targetLabel: "src/main.ts", name: "run", response: { id: "run", success: true, name: "run", kind: "function", range: { start_line: 1, end_line: 3 }, content: "function run() {\n  return 1;\n}", context_before: [], context_after: [], annotations: { calls_out: [], called_by: [] } } }, { targetLabel: "docs/guide.md", name: "missing", response: { id: "missing", success: false, code: "symbol_not_found", message: "symbol 'missing' not found" } }] } },
  { name: "zoom_multitarget_file_error_format", tool_name: "zoom", agent_args: { targets: [{ filePath: "src/main.ts", symbol: "run" }, { filePath: "missing.ts", symbol: "run" }] }, native_response_json: { id: "1", success: true, targets: [{ targetLabel: "src/main.ts", name: "run", response: { id: "run", success: true, name: "run", kind: "function", range: { start_line: 1, end_line: 3 }, content: "function run() {\n  return 1;\n}", context_before: [], context_after: [], annotations: { calls_out: [], called_by: [] } } }, { targetLabel: "missing.ts", name: "run", response: { id: "missing-file", success: false, code: "file_not_found", message: "file not found: <PROJECT_ROOT>/missing.ts" } }] } },
  { name: "zoom_large_container_member_menu_format", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "BigContainer" }, native_response_json: { id: "1", success: true, name: "BigContainer", kind: "class", range: { start_line: 1, end_line: 200 }, content: "class BigContainer (2 members) — member-signature menu; zoom a member for its body\nBigContainer\n  .BigContainer.methodOne(): number\n  .BigContainer.methodTwo(): void", context_before: [], context_after: [], annotations: { calls_out: [], called_by: [] } } },
  { name: "zoom_ambiguous_name_candidates_format", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "run" }, native_response_json: { id: "1", success: true, name: "run", kind: "ambiguous_symbol", content: "symbol 'run' is ambiguous (2 candidates) — zoom a qualified name for its body\n- run() — function run(): void\n- Worker.run() — method run(): Promise<void>", context_before: [], context_after: [], annotations: { calls_out: [], called_by: [] }, candidates: [{ name: "run", qualified_name: "run", kind: "function", signature: "run(): void" }, { name: "run", qualified_name: "Worker.run", kind: "method", signature: "run(): Promise<void>" }] } },
  { name: "zoom_single_symbol_not_found_error", tool_name: "zoom", agent_args: { filePath: "src/main.ts", symbols: "missing" }, native_response_json: { id: "1", success: false, code: "symbol_not_found", message: "symbol 'missing' not found, did you mean: [run]" } },
  { name: "callgraph_callers_format", tool_name: "callgraph", agent_args: { op: "callers", filePath: "src/main.ts", symbol: "leaf" }, native_response_json: { id: "1", success: true, total_callers: 3, depth_limited: true, truncated: 2, hub_summary: { message: "Showing first 20 callers; 7 omitted high-fan-in callers." }, callers: [{ file: `${PROJECT_ROOT}/src/main.ts`, callers: [{ symbol: "run", line: 12 }, { symbol: "run", line: 9 }, { symbol: "fallback", line: 30, resolved_by: "name_match" }] }, { file: `${HOME_ROOT}/aft-callgraph-home.ts`, callers: [{ symbol: "homeCaller", line: 5 }] }] } },
  { name: "callgraph_call_tree_format", tool_name: "callgraph", agent_args: { op: "call_tree", filePath: "src/main.ts", symbol: "run", includeUnresolved: true }, native_response_json: { id: "1", success: true, name: "run", file: `${PROJECT_ROOT}/src/main.ts`, line: 1, depth_limited: true, truncated: 1, children: [{ name: "helper", file: `${PROJECT_ROOT}/src/helper.ts`, line: 4, resolved_by: "name_match", children: [{ name: "external", file: `${PROJECT_ROOT}/src/helper.ts`, line: 5, resolved: false, children: [] }] }] } },
  { name: "callgraph_call_tree_unresolved_collapse", tool_name: "callgraph", agent_args: { op: "call_tree", filePath: "src/main.ts", symbol: "run" }, native_response_json: { id: "1", success: true, name: "run", file: `${PROJECT_ROOT}/src/main.ts`, line: 1, children: [{ name: "alpha", file: `${PROJECT_ROOT}/src/main.ts`, line: 2, resolved: false, children: [] }, { name: "beta", file: `${PROJECT_ROOT}/src/main.ts`, line: 3, resolved: false, children: [] }, { name: "gamma", file: `${PROJECT_ROOT}/src/main.ts`, line: 4, resolved: false, children: [] }, { name: "delta", file: `${PROJECT_ROOT}/src/main.ts`, line: 5, resolved: false, children: [] }, { name: "epsilon", file: `${PROJECT_ROOT}/src/main.ts`, line: 6, resolved: false, children: [] }, { name: "zeta", file: `${PROJECT_ROOT}/src/main.ts`, line: 7, resolved: false, children: [] }, { name: "eta", file: `${PROJECT_ROOT}/src/main.ts`, line: 8, resolved: false, children: [] }, { name: "theta", file: `${PROJECT_ROOT}/src/main.ts`, line: 9, resolved: false, children: [] }, { name: "iota", file: `${PROJECT_ROOT}/src/main.ts`, line: 10, resolved: false, children: [] }, { name: "kappa", file: `${PROJECT_ROOT}/src/main.ts`, line: 11, resolved: false, children: [] }, { name: "lambda", file: `${PROJECT_ROOT}/src/main.ts`, line: 12, resolved: false, children: [] }, { name: "project", file: `${PROJECT_ROOT}/src/project.ts`, line: 13, resolved: true, children: [] }] } },
  { name: "callgraph_trace_to_symbol_format", tool_name: "callgraph", agent_args: { op: "trace_to_symbol", filePath: "src/main.ts", symbol: "run", toSymbol: "leaf" }, native_response_json: { id: "1", success: true, complete: true, path: [{ symbol: "run", file: `${PROJECT_ROOT}/src/main.ts`, line: 1 }, { symbol: "middle", file: `${PROJECT_ROOT}/src/middle.ts`, line: 8, resolved_by: "name_match" }, { symbol: "leaf", file: `${PROJECT_ROOT}/src/leaf.ts`, line: 3 }] } },
  { name: "callgraph_trace_to_format", tool_name: "callgraph", agent_args: { op: "trace_to", filePath: "src/main.ts", symbol: "leaf" }, native_response_json: { id: "1", success: true, total_paths: 2, entry_points_found: 1, max_depth_reached: true, truncated_paths: 1, hub_summary: { message: "Showing first 20 paths; 3 omitted high-fan-in paths." }, paths: [{ hops: [{ symbol: "entry", file: `${PROJECT_ROOT}/src/entry.ts`, line: 1, is_entry_point: true }, { symbol: "leaf", file: `${PROJECT_ROOT}/src/main.ts`, line: 20, resolved_by: "name_match" }] }] } },
  { name: "callgraph_impact_format", tool_name: "callgraph", agent_args: { op: "impact", filePath: "src/main.ts", symbol: "run" }, native_response_json: { id: "1", success: true, total_affected: 2, affected_files: 1, depth_limited: false, hub_summary: { message: "Showing first 20 impacted call sites; 4 omitted high-fan-in callers." }, callers: [{ caller_file: `${PROJECT_ROOT}/src/main.ts`, caller_symbol: "entry", line: 10, is_entry_point: true, call_expression: "run(value)", parameters: ["value: string", "flag?: boolean"], resolved_by: "name_match" }] } },
  { name: "callgraph_trace_data_format", tool_name: "callgraph", agent_args: { op: "trace_data", filePath: "src/main.ts", symbol: "run", expression: "value" }, native_response_json: { id: "1", success: true, depth_limited: true, hops: [{ variable: "value", flow_type: "origin", symbol: "run", file: `${PROJECT_ROOT}/src/main.ts`, line: 2 }, { variable: "input", flow_type: "param", symbol: "helper", file: `${PROJECT_ROOT}/src/helper.ts`, line: 7, approximate: true, resolved_by: "name_match" }] } },
  { name: "callgraph_symbol_not_found_error", tool_name: "callgraph", agent_args: { op: "callers", filePath: "src/main.ts", symbol: "missing" }, native_response_json: { id: "1", success: false, code: "symbol_not_found", message: "callers: symbol 'missing' not found" } },
  { name: "callgraph_ambiguous_target_error", tool_name: "callgraph", agent_args: { op: "trace_to_symbol", filePath: "src/main.ts", symbol: "run", toSymbol: "leaf" }, native_response_json: { id: "1", success: false, code: "ambiguous_target", message: "trace_to_symbol: target symbol 'leaf' exists in multiple files; pass 'toFile' to disambiguate", candidates: [{ file: `${PROJECT_ROOT}/src/leaf.ts`, line: 3, symbol: "leaf" }, { file: `${PROJECT_ROOT}/src/other_leaf.ts`, line: 9, symbol: "leaf" }] } },
  { name: "callgraph_building_error", tool_name: "callgraph", agent_args: { op: "callers", filePath: "src/main.ts", symbol: "run" }, native_response_json: { id: "1", success: false, code: "callgraph_building", message: "callers: call graph is still building" } },
];

setupProjectRoot();
const onlyIndex = process.argv.indexOf("--only");
const onlyFilter = onlyIndex >= 0 ? process.argv[onlyIndex + 1] : undefined;
if (onlyIndex >= 0 && (!onlyFilter || onlyFilter.startsWith("--"))) {
  throw new Error("--only requires a fixture-name substring");
}

if (!onlyFilter) {
  rmSync(FIXTURES_ROOT, { recursive: true, force: true });
}
mkdirSync(FIXTURES_ROOT, { recursive: true });

const translateCases = onlyFilter
  ? TRANSLATE_CASES.filter((caseDef) => caseDef.name.includes(onlyFilter))
  : TRANSLATE_CASES;
const formatCases = onlyFilter
  ? FORMAT_CASES.filter((caseDef) => caseDef.name.includes(onlyFilter))
  : FORMAT_CASES;

for (const caseDef of translateCases) {
  await captureTranslateCase(caseDef);
}
for (const caseDef of formatCases) {
  await captureFormatCase(caseDef);
}

console.log(
  `Wrote ${translateCases.length} translate cases and ${formatCases.length} format cases under ${FIXTURES_ROOT}`,
);
